##Machine learning Requirements

(1) No missing values

(2) No characters values

(3) Correlations between variables

(4) Scaling between variable's data

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/My\ Drive

/content/drive/My Drive


In [3]:
import pandas as pd
import numpy as np

In [5]:
dataset = pd.read_csv('/content/drive/MyDrive/LAB VI SEM/FML Lab/sample.csv')

In [6]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [7]:
dataset.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [8]:
x=dataset.iloc[:,:-1]
y=dataset.iloc[:,3]

In [14]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy='mean')
x=imp.fit_transform(x.iloc[:,1:3])
print(x)

[[4.40000000e+01 7.20000000e+04]
 [2.70000000e+01 4.80000000e+04]
 [3.00000000e+01 5.40000000e+04]
 [3.80000000e+01 6.10000000e+04]
 [4.00000000e+01 6.37777778e+04]
 [3.50000000e+01 5.80000000e+04]
 [3.87777778e+01 5.20000000e+04]
 [4.80000000e+01 7.90000000e+04]
 [5.00000000e+01 8.30000000e+04]
 [3.70000000e+01 6.70000000e+04]]


## Handle Categorical values if present

In [15]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
x[:,0]=LE.fit_transform(x[:,0])

In [16]:
x

array([[7.00000000e+00, 7.20000000e+04],
       [0.00000000e+00, 4.80000000e+04],
       [1.00000000e+00, 5.40000000e+04],
       [4.00000000e+00, 6.10000000e+04],
       [6.00000000e+00, 6.37777778e+04],
       [2.00000000e+00, 5.80000000e+04],
       [5.00000000e+00, 5.20000000e+04],
       [8.00000000e+00, 7.90000000e+04],
       [9.00000000e+00, 8.30000000e+04],
       [3.00000000e+00, 6.70000000e+04]])

In [17]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [18]:
y=LE.fit_transform(y)

In [19]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## Apply OneHotEncoding if number of Catogories more than 2

## Why we are using OneHotEncoder?
-> Imagine if you have a 3 categorical values like in our dataset so we take France as 1 , Germany as 2 and Spain as 3 , so the problem is when model calculate the average ,it will something like 1+3 = 4/2 = 2, means accoring to your model average of France and Germany together is Spain

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
transform =  ColumnTransformer([("norm1",OneHotEncoder(),[0])], remainder = 'passthrough')
x = transform.fit_transform(x)
x

## Split the data into Train & Test

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
x_train

## Apply Standard Scaler
* y = (x – mean) / standard_deviation
* mean = sum(x) / count(x)
* standard_deviation = sqrt( sum( (x – mean)^2 ) / count(x))

In [ ]:
from sklearn.preprocessing import StandardScaler
SC = StandardScaler()
x_train[:,3:5]=SC.fit_transform(x_train[:,3:5])
x_train

In [ ]:
print("Orignal Data:\n",dataset)

In [ ]:
print("ML Needed data Data:\n")
x_train